### PR TITLE
[WIP] Jc/actions

### PR DESCRIPTION
**Pull request by jwscook**
github actions ci-workflow.yml.

### CODE REVIEW

**Comment by jwscook** [comment]
As it stands, Actions runs and fails on the tests on julia v1.5. 

Actions errors out before the testing step on v1.0

```julia
> julia --project -e 'using Pkg; Pkg.Registry.add("General")'
ERROR: UndefVarError: Registry not defined
```

and I don't know why. I just tried it on a fresh download of v1.0 and that worked.

**Comment by jwscook** [comment]
Shall we merge this in and come back to make further improvements later?

**Comment by AnHeuermann** [comment]
I'll add GitHub's CI to this repository later today. Not sure who can actually change CI.

Also I still need to figure out a way that the test will pass if no new tests are failing (only the one that were failing before).

**Comment by AnHeuermann** [comment]
I have created a new branch where I added your ci-workflow.yml and played around with it and now merged #58.
I really appreciate your help on this one!

While playing around with the yml I think I found one of the major problems to be in the CSV.jl package we are using. I changed the package and disabled the tests for now. I think I will just remove it completely and use a docker image with OpenModelica to verify the results, similar to what I did in https://github.com/OpenModelica/OMSimulator/blob/master/testsuite/fmi-cross-check/validateResults.py#L56-L74.
Creating a function to verify result is not straight forward and we only use it for test verification. No need to implement it in Julia.

**Comment by jwscook** [comment]
Good plan to make the package simpler.

**Pull request closed without merging**
