### PR TITLE
Use CBindings and other things that are hopefully improvements

### PR DESCRIPTION
**Pull request by jwscook**
I've done these things to enable me to run the bouncing ball co simulation fmu. 

This will need a review by someone who uses the other parts of the package to make sure it's all in order, which it probably isn't right now.

### CODE REVIEW

**Review by AnHeuermann — COMMENTED** [review]
This is looking very promising!

I like that you created FMI2CTypes.jl and moved types into that file. I'll finish #55 and then we can see what the CI thinks about this PR.

If I see it correctly there is no way yet to simulate a CS FMU, is that correct?

**Comment by jwscook** [comment]
All the calls are wrapped to run a co-simulation except maybe a couple like the ones about re-running a time step etc. 

I've run a co simulation fmu using the library so it's nearly there.

**Comment by jwscook** [comment]
Could we merge this in having resolved the conflicts (which I'm not able to do because I don't have write access)? I'm not going to get around to writing the CS wrapper for a little bit and I wouldn't want these changes to go stale.

**Comment by AnHeuermann** [comment]
You don't need write access. You can merge AnHeuermann:master into your branch jwscook:master and resolve the conflict and push your merge commit. That should be enough.

And then we can have a look at what the CI reports on this PR.

**Comment by jwscook** [comment]
Yeah I know. It's just easier to do it on github.com

**Comment by jwscook** [comment]
Looks like it's failing because a dependency needs `libgfortran3` but can't find it.

**Comment by AnHeuermann** [comment]
Oh yeah. That is because the GitHub runners are now using Ubuntu Focal which doesn't have libgfortran3. I was affraid that this happens. I'll change the runners to `ubuntu-18.04` later today.

**Comment by jwscook** [comment]
This now fails in the same places as #60

**Comment by jwscook** [comment]
@AnHeuermann is there anything outstanding preventing this from being merged?

**Comment by AnHeuermann** [comment]
Thank you for the help! Currently I'm very busy with personal stuff, but eventually I will update the test to run some CS FMUs from the fmi cross check.

**Comment by jwscook** [comment]
No problem! I'm glad to have been able to help.

**Pull request merged**
